apiVersion: v1
data:
  config.yaml: |
    billing_config:
      # if stop_pod is false, user's pods will not be stopped
      # turn on this option on production environment
      stop_pod: true
      test_env: true
      deployment_mode: "standard"

      # service email receiver
      service_email: ""

      # specify calculate cost time, format is "15:4"
      billing_time: ""

      # calculate cost every several minutes
      # if billing_time is not "", it should be n * 60 or n * 1440 (when > 1440)
      # if billing_time is "", 1440 % billing_interval should be 0
      billing_interval: 60

      # retrive pod state from k8s and save to redis every several minutes
      sync_interval: 60

      # if check_all_namespaces is false, billing server will only check test_namespace's cost
      check_all_namespaces: true
      test_namespace: ""
      system_namespace: "kube-system,system-monitoring,system-tce"

      # available values: debug, info, error
      log_level: info

    redis_config:
      server: "192.168.2.101:6379"
      password: "stor123"

    db_config:
      # "mysql" or "postgres"
      type: "mysql"
      host: "192.168.2.120"
      port: "5860"
      user: "root"
      password: "stor123;"
      # default db name
      name: "lxaieasier"
kind: ConfigMap
metadata:
  name: billing-config
  namespace: kube-system