apiVersion: apps/v1
kind: Deployment
metadata:
  name: billing-job
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: billing-job
  template:
    metadata:
      labels:
        app: billing-job
    spec:
      containers:
        - image: 192.168.2.123:30080/system/billing-job:v0.10.1    #修改成目标环境的Habor地址
          imagePullPolicy: Always
          name: manager
          resources:
            limits:
              cpu: 4
              memory: 128Mi
            requests:
              cpu: 4
              memory: 128Mi
          volumeMounts:
            - name: config
              mountPath: /root/config.yaml
              subPath: config.yaml
      restartPolicy: Always
      terminationGracePeriodSeconds: 10
      hostAliases:
        - ip: "192.168.2.120"          #修改成集群api-server的IP
          hostnames:
            - "lb.kubesphere.local"     #需要修改成集群的host
      nodeSelector:
        node-role.kubernetes.io/control-plane: ""
      tolerations:
        - key: system/node-group
          operator: Exists
      volumes:
        - name: config
          configMap:
            name: billing-config
